### ISSUE TITLE
build生成的Index.html 动态引入的css和js会出现重复引入

### ISSUE THREAD

**Issue by muyi0728** [wqzwh/blog#1]
![image](https://user-images.githubusercontent.com/23134854/43196193-c354d784-9039-11e8-8882-82aef485afa9.png)

**Comment by wqzwh** [comment]
@muyi0728  我的项目打包出来没发现有重复的，你能把你的webpack配置完整贴出来么

以下是我的项目打包截图

![image](https://user-images.githubusercontent.com/16662470/43990115-8ec44556-9d89-11e8-99fa-c1ddcfec5a71.png)

![image](https://user-images.githubusercontent.com/16662470/43990124-adc87648-9d89-11e8-8c72-b831548c0b27.png)
